services:
  client:
    build: 
      context: ./client/empmgmt
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: 
      context: ./server
    ports:
    - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: notsus
      POSTGRES_PASSWORD: Sidhu123104
      POSTGRES_DB: fsd
    ports:
      - "5432:5432"
